apisix:
  proxy_mode: http&stream
  node_listen:
    - port: 9080
  enable_admin: true
  stream_proxy:
    tcp:
      - 9100
    udp:
      - 9200

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9180
    admin_key:
      - name: admin
        key: "__ADMIN_KEY__"
        role: admin
    allow_admin:
      - 0.0.0.0/0
  etcd:
    host:
      - "http://__ETCD_HOST__:2379"
    prefix: "/apisix"
    timeout: 30