apisix:
  node_listen:
    - port: 9080
  enable_admin: true

deployment:
  role: traditional
  role_traditional:
    config_provider: yaml
  admin:
    admin_listen:
      port: 9180
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
